# Generated by Django 3.0.4 on 2020-04-28 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telemóvel não aparenta esta certo.', regex='^\\+?9?\\d{9}$')], verbose_name='Telemovel')),
                ('nif', models.IntegerField(max_length=9, verbose_name='NIF')),
                ('country', models.CharField(max_length=255, verbose_name='País')),
                ('state', models.CharField(max_length=255, verbose_name='Cidade')),
                ('hospital', models.CharField(max_length=255, verbose_name='Hospital')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('datastored', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator(message='O número de telemóvel não aparenta esta certo.', regex='^\\+?9?\\d{9}$')], verbose_name='Telemovel')),
                ('nif', models.IntegerField(max_length=9, verbose_name='NIF')),
                ('country', models.CharField(max_length=255, verbose_name='País')),
                ('state', models.CharField(max_length=255, verbose_name='Cidade')),
                ('nipc', models.CharField(max_length=255, verbose_name='NIPC')),
                ('compname', models.CharField(max_length=255, verbose_name='Nome Empresa')),
                ('cae', models.CharField(max_length=255, verbose_name='CAE')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('datastored', models.BooleanField()),
            ],
        ),
    ]
