# Generated by Django 3.0.4 on 2020-04-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='nif',
            field=models.CharField(max_length=9, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nif',
            field=models.CharField(max_length=9, verbose_name='NIF'),
        ),
    ]
