# Generated by Django 3.0.4 on 2020-05-01 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200501_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='hospital',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Apelido'),
            preserve_default=False,
        ),
    ]
