# Generated by Django 3.0.4 on 2020-05-02 16:25

from django.db import migrations
import django_countries.fields
import vies.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200502_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nif',
            field=vies.models.VATINField(blank=True, max_length=14, null=True),
        ),
    ]
