# Generated by Django 3.0.4 on 2020-05-03 22:39

from django.db import migrations
import vies.models
import vies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20200502_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='nif',
            field=vies.models.VATINField(max_length=14, validators=[vies.validators.VATINValidator(validate=True, verify=True)]),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nif',
            field=vies.models.VATINField(max_length=14, validators=[vies.validators.VATINValidator(validate=True, verify=True)]),
        ),
    ]
