# Generated by Django 3.0.4 on 2020-05-04 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200503_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='nif',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='O NIF não está correto', regex='^.{9}$')]),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nif',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='nomatch', message='O NIF não está correto', regex='^.{9}$')]),
        ),
    ]
