# Generated by Django 3.0.4 on 2020-05-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='country',
        ),
    ]
