# Generated by Django 3.0.4 on 2020-05-05 22:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200505_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
