# Generated by Django 3.0.4 on 2020-05-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_pedido_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
