# Generated by Django 3.0.4 on 2020-05-09 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='Portugal', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.City')),
            ],
        ),
    ]
