# Generated by Django 3.0.4 on 2020-05-10 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20200510_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=4000)),
                ('status', models.CharField(default='Criado', max_length=300)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.Pedido')),
            ],
        ),
    ]
