# Generated by Django 3.0.4 on 2020-05-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_resposta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalname',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='HospitalName',
        ),
    ]
