# Generated by Django 3.0.4 on 2020-05-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200513_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='titulo',
            field=models.CharField(default='Novo Pedido Criado', max_length=50),
        ),
    ]
