# Generated by Django 3.0.4 on 2020-05-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_pedido_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='status',
        ),
    ]
