# Generated by Django 3.0.4 on 2020-05-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_pedido_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='user',
        ),
        migrations.AddField(
            model_name='pedido',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resposta',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
